#server:
#  prot: 8081
#spring:
#  profiles: Development Environment
#    active: Development Environment
#---
#server:
#  prot: 8083
#spring:
#  profiles: Test Environment
#---
#server:
#  prot: 8084
#spring:
#  profiles: Production Environment

#person:
#  last-name: zhangsan
#  age: 18
#  boss: false
#  birth: 2018/12/12
#  maps: {k1: v1,k2: 12}
#  lists:
#    - lisi
#    - zhaoliu
#  dog:
#    name: 狗
#    age: 2
